name: Generate Readme Aura Layout

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Readme Aura Paintbrush
        uses: collectioneur/readme-aura@main
        with:
          github_token: ${{ secrets.README_AURA_TOKEN }}
